language: csharp
solution: ProtobufGenerator.sln

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - time dotnet restore && time dotnet build -c Release src/**/project.json && time dotnet test test/**/project.json;